from enum import Enum


class STAGE(Enum):
  START = 0
  NEXT_PARAM_CITY = 1
  NEXT_PARAM_CATEGORY = 2
  NEXT_PARAM_POSITION = 3
  NEXT_PARAM_MIN_SALARY = 4
  NEXT_PARAM_EXPERIENCE = 5
  NEXT_PARAM_LANGUAGE = 6
  END_OF_PROFILE_FILLING = 7
  RECEIVING_VACANCIES = 8
  START_SEARCH = 9
  START_SEARCHING_FOR_NEW_VACANCIES = 10
  CREATE_REQUEST = 11
  MY_REQUESTS = 12
  PRICING = 13
  ABOUT_BOT = 14
  CONTACTS = 15
  CREATE_UNIQUE_VACANCY = 16
  CREATE_UV_ADD_JOB_TITLE = 17
  CREATE_UV_ADD_CATEGORY = 18
  CREATE_UV_NEXT_PARAM_CATEGORY = 19
  CREATE_UV_ADD_COMPANY_NAME = 20
  CREATE_UV_ADD_DESCRIPTION = 21
  CREATE_UV_ADD_SALARY = 22
  CREATE_UV_ADD_EXPERIENCE = 23
  CREATE_UV_ADD_CITY = 24
  CREATE_UV_ADD_CONTACT = 25
  CREATE_UV_ADD_POSITION = 26

